/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blackbox.h"

bool_t
xdr_paths (XDR *xdrs, paths *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->path1, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->path2, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
