/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "blackbox.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <fcntl.h>
#include <string.h>


char*
blackbox_prog_1(int num1, int num2, char *path, char *host)
{
	CLIENT *clnt;
	char * *result_1;
	arguments  blackbox_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BLACKBOX_PROG, BLACKBOX_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	blackbox_1_arg.num1 = num1;
	blackbox_1_arg.num2 = num2;
	strcpy(blackbox_1_arg.path, path);
	result_1 = blackbox_1(&blackbox_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		return *result_1;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	FILE *fp = fopen(argv[2], "a");
	int file = open(argv[2], O_WRONLY | O_APPEND, 0777);
	if (file == -1) {
		return 2;
	}

	char *result;


	int a;
	int b;

	scanf("%d", &a);
	scanf("%d", &b);

	if (argc < 4) {
		printf ("usage: %s path1 path2 server_host\n", argv[0]);
		exit (1);
	}
	host = argv[3];
	result = blackbox_prog_1 (a, b, argv[1], host);

	fprintf(fp, "%s", result);

exit (0);
}
