/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "blackbox.h"


void
blackbox_prog_1(char *host, char *pathone, char *pathtwo)
{
	CLIENT *clnt;
	int  *result_1;
	paths  blackbox_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BLACKBOX_PROG, BLACKBOX_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	blackbox_1_arg.path1 = pathone;
	blackbox_1_arg.path2 = pathtwo;
	result_1 = blackbox_1(&blackbox_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Result = %d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s path_1 path_2 server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	blackbox_prog_1 (host, argv[2], argv[3]);
exit (0);
}
