/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLACKBOX_H_RPCGEN
#define _BLACKBOX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arguments {
	int num1;
	int num2;
	char path[200];
};
typedef struct arguments arguments;

#define BLACKBOX_PROG 0x12345678
#define BLACKBOX_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define blackbox 1
extern  char ** blackbox_1(arguments *, CLIENT *);
extern  char ** blackbox_1_svc(arguments *, struct svc_req *);
extern int blackbox_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define blackbox 1
extern  char ** blackbox_1();
extern  char ** blackbox_1_svc();
extern int blackbox_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arguments (XDR *, arguments*);

#else /* K&R C */
extern bool_t xdr_arguments ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BLACKBOX_H_RPCGEN */
